### ISSUE TITLE
Zsh failing to install

### ISSUE THREAD

**Issue by iloveitaly** [catthehacker/docker_images#138]
I'm using `tecolicom/actions-use-apt-tools@v1` to install some packages on `ubuntu-latest`. It's working fine on the normal GHA runners ([this example repo](https://github.com/iloveitaly/python-starter-template/actions/runs/12097294142/job/33732514227) within the `common-setup` action), but failing here:

```
[Build & Publish/Backend] ⭐ Run Main sudo apt-get install -y zsh libnss3-tools
[Build & Publish/Backend]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1-composite-1-composite-self-install.sh] user= workdir=
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
| Package zsh is not available, but is referred to by another package.
| This may mean that the package is missing, has been obsoleted, or
| is only available from another source
|
| E: Package 'zsh' has no installation candidate
| E: Unable to locate package libnss3-tools
```

Any idea what is going wrong here?

**Comment by catthehacker** [comment]
I would not recommend using random actions to do simplest thing on Ubuntu, in this case indexes are outdated because https://github.com/tecolicom/actions-use-apt-tools doesn't update them.

**Comment by iloveitaly** [comment]
Makes sense. Curious: is the overall goal of act + this image to be compatible with ubuntu-latest such that users can easily reproduce use either environment?

**Comment by catthehacker** [comment]
> Curious: is the overall goal of act + this image to be compatible with ubuntu-latest such that users can easily reproduce use either environment?

act is supposed to be compatible with GHA design, but it does have few hacks and workarounds for docker images used with it so it works like GHA runners.
The images (this repo) are meant to be most compatible but not complete, they provide various configs and environment variables to make it work like `ubuntu-latest` but including all the software in a manual way is too much work and not everyone will like 40GB+ docker images.

**Comment by catthehacker** [comment]
I do reserve the right to make small changes that might be breaking or look breaking, like installing packages.

That's because GHA runners are constantly re-built every week, so what they contain changes.
In your case you don't have `apt update`/`apt-get update` so it will be missing references to dependencies as my images have all apt indexes cleaned during build.

This is to prevent issues in GHA because that problem will occur there as well but it depends heavily on the time when workflow is executed
https://github.com/actions/runner-images/issues/4660#issuecomment-985410278
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners
